---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "project-ta-v1-hpa-ybvm"
  namespace: "shlink"
  labels:
    app: "project-ta-v1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "project-ta-v1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80